#!/usr/bin/env ruby
# vim: set filetype=ruby:
$: << File.expand_path("../../lib/", __FILE__)

require 'anabolic_steroid'
require 'anabolic_steroid/application'

@app = AnabolicSteroid::Application.new

extend Forwardable
def_delegator(:@app, :config)
def_delegator(:@app, :entry)
def_delegator(:@app, :post_process)

open('Steroidfile', 'r') do |f|
  eval(f.read)
end
@app.run

def usage
  puts 'usage: anabolic_steroid'
end
